[tools]
asphalt = "jacktabscode/asphalt@0.9.1"
darklua = "howmanysmall/darklua@0.17.0"
lunar = "corecii/lunar@0.1.0"
lune = "lune-org/lune@0.9.3"
rbxcloud = "sleitnick/rbxcloud@0.17.0"
rojo = "rojo-rbx/rojo@7.5.1"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
selene = "kampfkarren/selene@0.28.0"
